import { MOCK_REPORT, type ReportSectionToggles } from "@/lib/reports/mockReportData";
import { REPORT_PREVIEW_ID } from "@/lib/reports/exportReport";
import PLSummarySection from "./ReportSections/PLSummarySection";
import OverviewSection from "./ReportSections/OverviewSection";
import BookingsSection from "./ReportSections/BookingsSection";
import PendingSection from "./ReportSections/PendingSection";
import ExpenseSection from "./ReportSections/ExpenseSection";
import DriverSection from "./ReportSections/DriverSection";
import RouteSection from "./ReportSections/RouteSection";
import CabSection from "./ReportSections/CabSection";
import RatingSection from "./ReportSections/RatingSection";
import CommSection from "./ReportSections/CommSection";
import PaymentSection from "./ReportSections/PaymentSection";
import BestCustomer from "./ReportSections/BestCustomer";
import BusiestDay from "./ReportSections/BusiestDay";
import PartnerSection from "./ReportSections/PartnerSection";
import GSTSection from "./ReportSections/GSTSection";
import CancelSection from "./ReportSections/CancelSection";

interface ReportPreviewProps {
  period: string;
  sections: ReportSectionToggles;
}

export default function ReportPreview({ period, sections }: ReportPreviewProps) {
  const data = MOCK_REPORT;

  return (
    <div
      id={REPORT_PREVIEW_ID}
      className="mx-auto max-w-[820px] rounded-2xl border border-report-border bg-report-bg text-report-text shadow-sm"
    >
      <div className="border-b border-report-border px-6 py-6">
        <p className="font-display text-2xl font-bold text-report-text">🚗 OBII CABS</p>
        <p className="text-sm text-report-text/60">One Booking — Infinite Independence</p>

        <p className="mt-4 text-lg font-semibold tracking-wide text-report-text">BUSINESS REPORT</p>
        <p className="mt-1 text-sm text-report-text/70">Period: {period}</p>
        <p className="text-sm text-report-text/70">Generated: {data.generated}</p>
      </div>

      <PLSummarySection pl={data.pl} />
      <OverviewSection overview={data.overview} />
      {sections.bookings && <BookingsSection bookings={data.closedBookings} />}
      {sections.pending && <PendingSection leads={data.pendingLeads} />}
      {sections.expenses && <ExpenseSection expenses={data.expenses} />}
      {sections.drivers && <DriverSection drivers={data.drivers} />}
      {sections.routes && <RouteSection routes={data.routes} />}
      {sections.cabs && <CabSection cabs={data.cabs} />}
      {sections.ratings && <RatingSection ratings={data.ratings} />}
      {sections.communication && <CommSection communication={data.communication} />}
      {sections.payment && <PaymentSection paymentMode={data.paymentMode} />}
      {sections.bestCustomer && <BestCustomer bestCustomer={data.bestCustomer} />}
      {sections.busiestDay && <BusiestDay busiestDay={data.busiestDay} />}
      {sections.partners && (
        <PartnerSection
          partners={data.partners}
          totalCommission={data.pl.partnerCommission}
          totalPayouts={data.pl.partnerPayouts}
        />
      )}
      {sections.gst && <GSTSection gst={data.gst} />}
      {sections.cancellations && (
        <CancelSection cancellations={data.cancellations} leadsReceived={data.overview.leadsReceived} />
      )}

      <div className="px-6 py-5 text-center text-xs text-report-text/40">
        Generated by Obii Cabs Owner Dashboard · obiicabs.com
      </div>
    </div>
  );
}
